'use client';

import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'fr';

type TranslationKeys = keyof typeof translations.en;

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: TranslationKeys, params?: Record<string, string | number>) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation dictionaries
const translations = {
  en: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.reviews': 'Reviews',
    'nav.analytics': 'Analytics',
    'nav.business': 'My Business',
    'nav.social': 'Social Media',
    'nav.video': 'Video Generator',
    'nav.affiliation': 'Affiliation',
    'nav.help': 'Help',
    'nav.settings': 'Settings',
    
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.totalReviews': 'Total Reviews',
    'dashboard.averageRating': 'Average Rating',
    'dashboard.pendingResponses': 'Pending Responses',
    'dashboard.autoApprovalRate': 'Auto-Approval Rate',
    'dashboard.allPlatforms': 'All platforms combined',
    'dashboard.acrossPlatforms': 'Across all platforms',
    'dashboard.awaitingApproval': 'Awaiting approval',
    'dashboard.aiConfidence': 'AI confidence threshold',
    'dashboard.recentReviews': 'Recent Reviews',
    'dashboard.urgentReviews': 'Urgent Reviews Requiring Attention',
    'dashboard.performanceOverview': 'Performance Overview',
    'dashboard.sentimentAnalysis': 'Sentiment Analysis',
    'dashboard.weeklyActivity': 'Weekly Activity',
    'dashboard.responseTimes': 'Response Times',
    'dashboard.scrapeReviews': 'Scrape Reviews',
    'dashboard.scrapingInProgress': 'Scraping in progress...',
    'dashboard.newReviews': 'new',
    'dashboard.urgentAlert': 'urgent',
    'dashboard.urgentDescription': 'review(s) with low ratings need immediate response.',
    
    // Reviews
    'reviews.title': 'Reviews',
    'reviews.description': 'Manage and respond to customer reviews',
    'reviews.export': 'Export',
    'reviews.total': 'Total',
    'reviews.filters': 'Filters',
    'reviews.searchPlaceholder': 'Search reviews...',
    'reviews.platform': 'Platform',
    'reviews.allPlatforms': 'All Platforms',
    'reviews.status': 'Status',
    'reviews.allStatus': 'All Status',
    'reviews.pending': 'Pending',
    'reviews.approved': 'Approved',
    'reviews.published': 'Published',
    'reviews.rejected': 'Rejected',
    'reviews.rating': 'Rating',
    'reviews.allRatings': 'All Ratings',
    'reviews.tags': 'Tags',
    'reviews.allTags': 'All Tags',
    'reviews.clearFilters': 'Clear Filters',
    'reviews.noMatches': 'No reviews match your current filters.',
    'reviews.aiResponse': 'AI Response',
    'reviews.confidence': 'confidence',
    'reviews.saveChanges': 'Save Changes',
    'reviews.cancel': 'Cancel',
    'reviews.approve': 'Approve',
    'reviews.reject': 'Reject',
    'reviews.showMore': 'Show more',
    'reviews.showLess': 'Show less',
    'reviews.urgent': 'Urgent',
    'reviews.viewOriginal': 'View Original',
    'reviews.editResponse': 'Edit Response',
    'reviews.stars': 'Stars',
    'reviews.star': 'Star',
    
    // Analytics
    'analytics.title': 'Analytics',
    'analytics.description': 'Insights and performance metrics for your reviews',
    'analytics.reviewsByPlatform': 'Reviews by Platform',
    'analytics.ratingDistribution': 'Rating Distribution',
    'analytics.reviewTrends': 'Review Trends',
    'analytics.platformPerformance': 'Platform Performance Details',
    'analytics.totalReviews': 'total reviews',
    'analytics.averageRating': 'Average Rating',
    'analytics.acrossPlatforms': 'Across all platforms',
    'analytics.ofTotal': 'of total',
    'analytics.growthRate': 'Growth Rate',
    'analytics.thisMonth': 'This month',
    'analytics.avgResponseTime': 'Avg Response Time',
    'analytics.timeToRespond': 'Time to respond',
    'analytics.allTime': 'All time',
    'analytics.responseRate': 'Response Rate',
    'analytics.aiApprovalRate': 'AI approval rate',
    'analytics.pendingReviews': 'Pending Reviews',
    'analytics.awaitingAction': 'Awaiting action',
    
    // Business
    'business.title': 'My Business Profile',
    'business.description': 'Complete your business information to improve Google ranking and SEO',
    'business.gmbConnected': 'Connected to Google My Business - Manage your profile and improve SEO',
    'business.saveChanges': 'Save Changes',
    'business.openGMB': 'Open GMB',
    'business.gmbSuccess': 'Google My Business Connected Successfully! 🎉',
    'business.gmbSuccessDesc': 'Your business data is now synced. You can manage your Google My Business profile directly from here.',
    'business.profileCompletion': 'Profile Completion',
    'business.excellentProfile': 'Excellent! Your profile is well optimized.',
    'business.goodProgress': 'Good progress! Add more details to improve ranking.',
    'business.completeProfile': 'Complete your profile to improve Google visibility.',
    'business.complete': 'Complete',
    'business.basicInfo': 'Basic Information',
    'business.contactInfo': 'Contact Information',
    'business.businessHours': 'Business Hours',
    'business.servicesOffered': 'Services Offered',
    'business.businessImages': 'Business Images',
    'business.businessAttributes': 'Business Attributes',
    'business.seoTips': 'SEO Optimization Tips',
    'business.businessName': 'Business Name',
    'business.primaryCategory': 'Primary Category',
    'business.subcategory': 'Subcategory',
    'business.businessDescription': 'Business Description',
    'business.phoneNumber': 'Phone Number',
    'business.emailAddress': 'Email Address',
    'business.websiteUrl': 'Website URL',
    'business.restaurant': 'Restaurant',
    'business.retailStore': 'Retail Store',
    'business.serviceBusiness': 'Service Business',
    'business.healthcare': 'Healthcare',
    'business.beautySpa': 'Beauty & Spa',
    'business.automotive': 'Automotive',
    'business.professionalServices': 'Professional Services',
    'business.entertainment': 'Entertainment',
    'business.liveSync': 'Live Sync',
    
    // Settings
    'settings.title': 'Settings',
    'settings.description': 'Configure your business profile and AI preferences',
    'settings.businessInfo': 'Business Information',
    'settings.platformConnections': 'Platform Connections',
    'settings.aiSettings': 'AI Response Settings',
    'settings.responseTemplates': 'Response Templates',
    'settings.notifications': 'Notifications',
    'settings.responseStyle': 'Response Style',
    'settings.autoApproval': 'Auto-Approval',
    'settings.urgentThreshold': 'Urgent Review Threshold',
    'settings.customPrompts': 'Custom AI Prompts',
    'settings.addPrompt': 'Add Prompt',
    'settings.addTemplate': 'Add Template',
    'settings.emailNotifications': 'Email Notifications',
    'settings.pushNotifications': 'Push Notifications',
    'settings.smsNotifications': 'SMS Notifications',
    'settings.businessName': 'Business Name',
    'settings.businessType': 'Business Type',
    'settings.address': 'Address',
    'settings.phone': 'Phone',
    'settings.website': 'Website',
    'settings.restaurant': 'Restaurant',
    'settings.retailStore': 'Retail Store',
    'settings.serviceBusiness': 'Service Business',
    'settings.healthcare': 'Healthcare',
    'settings.hospitality': 'Hospitality',
    'settings.professional': 'Professional',
    'settings.friendly': 'Friendly',
    'settings.casual': 'Casual',
    'settings.autoApprovalDesc': 'Automatically approve high-confidence responses',
    'settings.oneStarBelow': '1 star and below',
    'settings.twoStarsBelow': '2 stars and below',
    'settings.threeStarsBelow': '3 stars and below',
    'settings.emailNotificationsDesc': 'Receive email alerts for new reviews',
    'settings.pushNotificationsDesc': 'Browser push notifications',
    'settings.smsNotificationsDesc': 'Text message alerts for urgent reviews',
    
    // Help
    'help.title': 'Help & Onboarding',
    'help.description': 'Get started with Revally and find answers to your questions',
    'help.startTour': 'Start Guided Tour',
    'help.userGuide': 'User Guide',
    'help.videoTutorials': 'Video Tutorials',
    'help.faq': 'FAQ',
    'help.support': 'Support',
    'help.getSupport': 'Get Support',
    'help.chatTeam': 'Chat with our team',
    'help.stepByStep': 'Step-by-step instructions',
    'help.visualLearning': 'Visual learning resources',
    'help.videos': 'Videos',
    
    // Common
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.add': 'Add',
    'common.remove': 'Remove',
    'common.close': 'Close',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.finish': 'Finish',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.warning': 'Warning',
    'common.info': 'Info',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.ok': 'OK',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.sort': 'Sort',
    'common.view': 'View',
    'common.download': 'Download',
    'common.upload': 'Upload',
    'common.connect': 'Connect',
    'common.disconnect': 'Disconnect',
    'common.connected': 'Connected',
    'common.notConnected': 'Not Connected',
    'common.online': 'Online',
    'common.offline': 'Offline',
    'common.changes': 'Changes',
    
    // Store selector
    'store.noStoreSelected': 'No store selected',
    'store.liveMonitoring': 'Live Monitoring',
    'store.activelyMonitoring': 'Actively monitoring 3 platforms for new reviews',
    'store.reviews': 'reviews',
    
    // Header
    'header.notifications': 'Notifications',
    'header.markAllRead': 'Mark all read',
    'header.noNotifications': 'No notifications',
    'header.viewAll': 'View all notifications',
    'header.profile': 'Profile',
    'header.signOut': 'Sign out',
    'header.language': 'Language',
    
    // Onboarding
    'onboarding.welcome': 'Welcome to Revally',
    'onboarding.welcomeDesc': 'Let\'s set up your account and connect your business locations to start managing reviews with AI-powered responses',
    'onboarding.aiResponses': 'AI-Powered Responses',
    'onboarding.aiResponsesDesc': 'Automatically generate personalized responses to customer reviews with advanced AI',
    'onboarding.multiLocation': 'Multi-Location Management',
    'onboarding.multiLocationDesc': 'Manage reviews across all your business locations from one centralized dashboard',
    'onboarding.realTimeMonitoring': 'Real-Time Monitoring',
    'onboarding.realTimeMonitoringDesc': 'Get instant notifications when new reviews are posted across all platforms',
    'onboarding.quickSetup': 'Quick Setup Process',
    'onboarding.connectBusinesses': 'Connect Your Businesses',
    'onboarding.connectBusinessesDesc': 'Select your Google My Business locations to monitor',
    'onboarding.aiSetup': 'AI Setup',
    'onboarding.aiSetupDesc': 'Configure AI settings to match your brand voice',
    'onboarding.startManaging': 'Start Managing',
    'onboarding.startManagingDesc': 'Begin monitoring and responding to reviews',
    'onboarding.startSetup': 'Start Setup',
    'onboarding.selectBusinesses': 'Select Your Business Locations',
    'onboarding.selectBusinessesDesc': 'Choose the Google My Business locations you want to monitor with Revally. You can add or remove locations later in settings.',
    'onboarding.locationsSelected': 'locations selected',
    'onboarding.selectAtLeast': 'Select at least one location to continue',
    'onboarding.readyToConnect': 'Ready to connect',
    'onboarding.connectingBusinesses': 'Connecting Your Businesses',
    'onboarding.settingUpMonitoring': 'We\'re setting up monitoring for your selected locations...',
    'onboarding.connectedSuccessfully': 'Connected successfully',
    'onboarding.settingUpAI': 'Setting up AI monitoring...',
    'onboarding.setupComplete': 'Setup Complete! 🎉',
    'onboarding.businessesConnected': 'Your businesses are now connected and being monitored by Revally',
    'onboarding.whatHappensNext': 'What happens next?',
    'onboarding.aiWillMonitor': 'AI will start monitoring your reviews in real-time',
    'onboarding.receiveNotifications': 'You\'ll receive notifications for new reviews',
    'onboarding.aiResponsesGenerated': 'AI responses will be generated automatically',
    'onboarding.goToDashboard': 'Go to Dashboard',
    'onboarding.addMoreLater': 'You can always add more locations or modify settings later',
    'onboarding.connectSelected': 'Connect {count} Selected Business{plural}',
    'onboarding.verified': 'Verified',
  },
  fr: {
    // Navigation
    'nav.dashboard': 'Tableau de bord',
    'nav.reviews': 'Avis',
    'nav.analytics': 'Analyses',
    'nav.business': 'Mon Entreprise',
    'nav.social': 'Réseaux Sociaux',
    'nav.video': 'Générateur Vidéo',
    'nav.affiliation': 'Affiliation',
    'nav.help': 'Aide',
    'nav.settings': 'Paramètres',
    
    // Dashboard
    'dashboard.title': 'Tableau de bord',
    'dashboard.totalReviews': 'Total des avis',
    'dashboard.averageRating': 'Note moyenne',
    'dashboard.pendingResponses': 'Réponses en attente',
    'dashboard.autoApprovalRate': 'Taux d\'approbation auto',
    'dashboard.allPlatforms': 'Toutes plateformes confondues',
    'dashboard.acrossPlatforms': 'Sur toutes les plateformes',
    'dashboard.awaitingApproval': 'En attente d\'approbation',
    'dashboard.aiConfidence': 'Seuil de confiance IA',
    'dashboard.recentReviews': 'Avis récents',
    'dashboard.urgentReviews': 'Avis urgents nécessitant une attention',
    'dashboard.performanceOverview': 'Aperçu des performances',
    'dashboard.sentimentAnalysis': 'Analyse des sentiments',
    'dashboard.weeklyActivity': 'Activité hebdomadaire',
    'dashboard.responseTimes': 'Temps de réponse',
    'dashboard.scrapeReviews': 'Scraper les avis',
    'dashboard.scrapingInProgress': 'Scraping en cours...',
    'dashboard.newReviews': 'nouveaux',
    'dashboard.urgentAlert': 'urgent',
    'dashboard.urgentDescription': 'avis avec des notes faibles nécessitent une réponse immédiate.',
    
    // Reviews
    'reviews.title': 'Avis',
    'reviews.description': 'Gérer et répondre aux avis clients',
    'reviews.export': 'Exporter',
    'reviews.total': 'Total',
    'reviews.filters': 'Filtres',
    'reviews.searchPlaceholder': 'Rechercher des avis...',
    'reviews.platform': 'Plateforme',
    'reviews.allPlatforms': 'Toutes les plateformes',
    'reviews.status': 'Statut',
    'reviews.allStatus': 'Tous les statuts',
    'reviews.pending': 'En attente',
    'reviews.approved': 'Approuvé',
    'reviews.published': 'Publié',
    'reviews.rejected': 'Rejeté',
    'reviews.rating': 'Note',
    'reviews.allRatings': 'Toutes les notes',
    'reviews.tags': 'Tags',
    'reviews.allTags': 'Tous les tags',
    'reviews.clearFilters': 'Effacer les filtres',
    'reviews.noMatches': 'Aucun avis ne correspond à vos filtres actuels.',
    'reviews.aiResponse': 'Réponse IA',
    'reviews.confidence': 'confiance',
    'reviews.saveChanges': 'Enregistrer les modifications',
    'reviews.cancel': 'Annuler',
    'reviews.approve': 'Approuver',
    'reviews.reject': 'Rejeter',
    'reviews.showMore': 'Voir plus',
    'reviews.showLess': 'Voir moins',
    'reviews.urgent': 'Urgent',
    'reviews.viewOriginal': 'Voir l\'original',
    'reviews.editResponse': 'Modifier la réponse',
    'reviews.stars': 'Étoiles',
    'reviews.star': 'Étoile',
    
    // Analytics
    'analytics.title': 'Analyses',
    'analytics.description': 'Insights et métriques de performance pour vos avis',
    'analytics.reviewsByPlatform': 'Avis par plateforme',
    'analytics.ratingDistribution': 'Distribution des notes',
    'analytics.reviewTrends': 'Tendances des avis',
    'analytics.platformPerformance': 'Détails des performances par plateforme',
    'analytics.totalReviews': 'avis au total',
    'analytics.averageRating': 'Note moyenne',
    'analytics.acrossPlatforms': 'Sur toutes les plateformes',
    'analytics.ofTotal': 'du total',
    'analytics.growthRate': 'Taux de croissance',
    'analytics.thisMonth': 'Ce mois-ci',
    'analytics.avgResponseTime': 'Temps de réponse moyen',
    'analytics.timeToRespond': 'Temps pour répondre',
    'analytics.allTime': 'Depuis toujours',
    'analytics.responseRate': 'Taux de réponse',
    'analytics.aiApprovalRate': 'Taux d\'approbation IA',
    'analytics.pendingReviews': 'Avis en attente',
    'analytics.awaitingAction': 'En attente d\'action',
    
    // Business
    'business.title': 'Mon Profil d\'Entreprise',
    'business.description': 'Complétez les informations de votre entreprise pour améliorer le classement Google et le SEO',
    'business.gmbConnected': 'Connecté à Google My Business - Gérez votre profil et améliorez le SEO',
    'business.saveChanges': 'Enregistrer les modifications',
    'business.openGMB': 'Ouvrir GMB',
    'business.gmbSuccess': 'Google My Business connecté avec succès ! 🎉',
    'business.gmbSuccessDesc': 'Vos données d\'entreprise sont maintenant synchronisées. Vous pouvez gérer votre profil Google My Business directement depuis ici.',
    'business.profileCompletion': 'Complétude du profil',
    'business.excellentProfile': 'Excellent ! Votre profil est bien optimisé.',
    'business.goodProgress': 'Bon progrès ! Ajoutez plus de détails pour améliorer le classement.',
    'business.completeProfile': 'Complétez votre profil pour améliorer la visibilité Google.',
    'business.complete': 'Complet',
    'business.basicInfo': 'Informations de base',
    'business.contactInfo': 'Informations de contact',
    'business.businessHours': 'Heures d\'ouverture',
    'business.servicesOffered': 'Services offerts',
    'business.businessImages': 'Images de l\'entreprise',
    'business.businessAttributes': 'Attributs de l\'entreprise',
    'business.seoTips': 'Conseils d\'optimisation SEO',
    'business.businessName': 'Nom de l\'entreprise',
    'business.primaryCategory': 'Catégorie principale',
    'business.subcategory': 'Sous-catégorie',
    'business.businessDescription': 'Description de l\'entreprise',
    'business.phoneNumber': 'Numéro de téléphone',
    'business.emailAddress': 'Adresse email',
    'business.websiteUrl': 'URL du site web',
    'business.restaurant': 'Restaurant',
    'business.retailStore': 'Magasin de détail',
    'business.serviceBusiness': 'Entreprise de services',
    'business.healthcare': 'Santé',
    'business.beautySpa': 'Beauté & Spa',
    'business.automotive': 'Automobile',
    'business.professionalServices': 'Services professionnels',
    'business.entertainment': 'Divertissement',
    'business.liveSync': 'Synchronisation en direct',
    
    // Settings
    'settings.title': 'Paramètres',
    'settings.description': 'Configurez votre profil d\'entreprise et les préférences IA',
    'settings.businessInfo': 'Informations de l\'entreprise',
    'settings.platformConnections': 'Connexions aux plateformes',
    'settings.aiSettings': 'Paramètres de réponse IA',
    'settings.responseTemplates': 'Modèles de réponse',
    'settings.notifications': 'Notifications',
    'settings.responseStyle': 'Style de réponse',
    'settings.autoApproval': 'Approbation automatique',
    'settings.urgentThreshold': 'Seuil d\'avis urgent',
    'settings.customPrompts': 'Prompts IA personnalisés',
    'settings.addPrompt': 'Ajouter un prompt',
    'settings.addTemplate': 'Ajouter un modèle',
    'settings.emailNotifications': 'Notifications par email',
    'settings.pushNotifications': 'Notifications push',
    'settings.smsNotifications': 'Notifications SMS',
    'settings.businessName': 'Nom de l\'entreprise',
    'settings.businessType': 'Type d\'entreprise',
    'settings.address': 'Adresse',
    'settings.phone': 'Téléphone',
    'settings.website': 'Site web',
    'settings.restaurant': 'Restaurant',
    'settings.retailStore': 'Magasin de détail',
    'settings.serviceBusiness': 'Entreprise de services',
    'settings.healthcare': 'Santé',
    'settings.hospitality': 'Hôtellerie',
    'settings.professional': 'Professionnel',
    'settings.friendly': 'Amical',
    'settings.casual': 'Décontracté',
    'settings.autoApprovalDesc': 'Approuver automatiquement les réponses à haute confiance',
    'settings.oneStarBelow': '1 étoile et moins',
    'settings.twoStarsBelow': '2 étoiles et moins',
    'settings.threeStarsBelow': '3 étoiles et moins',
    'settings.emailNotificationsDesc': 'Recevoir des alertes par email pour les nouveaux avis',
    'settings.pushNotificationsDesc': 'Notifications push du navigateur',
    'settings.smsNotificationsDesc': 'Alertes SMS pour les avis urgents',
    
    // Help
    'help.title': 'Aide et Intégration',
    'help.description': 'Commencez avec Revally et trouvez des réponses à vos questions',
    'help.startTour': 'Commencer la visite guidée',
    'help.userGuide': 'Guide utilisateur',
    'help.videoTutorials': 'Tutoriels vidéo',
    'help.faq': 'FAQ',
    'help.support': 'Support',
    'help.getSupport': 'Obtenir de l\'aide',
    'help.chatTeam': 'Discuter avec notre équipe',
    'help.stepByStep': 'Instructions étape par étape',
    'help.visualLearning': 'Ressources d\'apprentissage visuel',
    'help.videos': 'Vidéos',
    
    // Common
    'common.save': 'Enregistrer',
    'common.cancel': 'Annuler',
    'common.edit': 'Modifier',
    'common.delete': 'Supprimer',
    'common.add': 'Ajouter',
    'common.remove': 'Retirer',
    'common.close': 'Fermer',
    'common.back': 'Retour',
    'common.next': 'Suivant',
    'common.finish': 'Terminer',
    'common.loading': 'Chargement...',
    'common.error': 'Erreur',
    'common.success': 'Succès',
    'common.warning': 'Avertissement',
    'common.info': 'Info',
    'common.yes': 'Oui',
    'common.no': 'Non',
    'common.ok': 'OK',
    'common.search': 'Rechercher',
    'common.filter': 'Filtrer',
    'common.sort': 'Trier',
    'common.view': 'Voir',
    'common.download': 'Télécharger',
    'common.upload': 'Téléverser',
    'common.connect': 'Connecter',
    'common.disconnect': 'Déconnecter',
    'common.connected': 'Connecté',
    'common.notConnected': 'Non connecté',
    'common.online': 'En ligne',
    'common.offline': 'Hors ligne',
    'common.changes': 'Modifications',
    
    // Store selector
    'store.noStoreSelected': 'Aucun magasin sélectionné',
    'store.liveMonitoring': 'Surveillance en direct',
    'store.activelyMonitoring': 'Surveillance active de 3 plateformes pour de nouveaux avis',
    'store.reviews': 'avis',
    
    // Header
    'header.notifications': 'Notifications',
    'header.markAllRead': 'Tout marquer comme lu',
    'header.noNotifications': 'Aucune notification',
    'header.viewAll': 'Voir toutes les notifications',
    'header.profile': 'Profil',
    'header.signOut': 'Se déconnecter',
    'header.language': 'Langue',
    
    // Onboarding
    'onboarding.welcome': 'Bienvenue sur Revally',
    'onboarding.welcomeDesc': 'Configurons votre compte et connectons vos emplacements d\'entreprise pour commencer à gérer les avis avec des réponses alimentées par l\'IA',
    'onboarding.aiResponses': 'Réponses alimentées par l\'IA',
    'onboarding.aiResponsesDesc': 'Générez automatiquement des réponses personnalisées aux avis clients avec une IA avancée',
    'onboarding.multiLocation': 'Gestion multi-emplacements',
    'onboarding.multiLocationDesc': 'Gérez les avis de tous vos emplacements d\'entreprise depuis un tableau de bord centralisé',
    'onboarding.realTimeMonitoring': 'Surveillance en temps réel',
    'onboarding.realTimeMonitoringDesc': 'Recevez des notifications instantanées lorsque de nouveaux avis sont publiés sur toutes les plateformes',
    'onboarding.quickSetup': 'Processus de configuration rapide',
    'onboarding.connectBusinesses': 'Connectez vos entreprises',
    'onboarding.connectBusinessesDesc': 'Sélectionnez vos emplacements Google My Business à surveiller',
    'onboarding.aiSetup': 'Configuration IA',
    'onboarding.aiSetupDesc': 'Configurez les paramètres IA pour correspondre à la voix de votre marque',
    'onboarding.startManaging': 'Commencer la gestion',
    'onboarding.startManagingDesc': 'Commencez à surveiller et répondre aux avis',
    'onboarding.startSetup': 'Commencer la configuration',
    'onboarding.selectBusinesses': 'Sélectionnez vos emplacements d\'entreprise',
    'onboarding.selectBusinessesDesc': 'Choisissez les emplacements Google My Business que vous souhaitez surveiller avec Revally. Vous pouvez ajouter ou supprimer des emplacements plus tard dans les paramètres.',
    'onboarding.locationsSelected': 'emplacements sélectionnés',
    'onboarding.selectAtLeast': 'Sélectionnez au moins un emplacement pour continuer',
    'onboarding.readyToConnect': 'Prêt à connecter',
    'onboarding.connectingBusinesses': 'Connexion de vos entreprises',
    'onboarding.settingUpMonitoring': 'Nous configurons la surveillance pour vos emplacements sélectionnés...',
    'onboarding.connectedSuccessfully': 'Connecté avec succès',
    'onboarding.settingUpAI': 'Configuration de la surveillance IA...',
    'onboarding.setupComplete': 'Configuration terminée ! 🎉',
    'onboarding.businessesConnected': 'Vos entreprises sont maintenant connectées et surveillées par Revally',
    'onboarding.whatHappensNext': 'Que se passe-t-il ensuite ?',
    'onboarding.aiWillMonitor': 'L\'IA commencera à surveiller vos avis en temps réel',
    'onboarding.receiveNotifications': 'Vous recevrez des notifications pour les nouveaux avis',
    'onboarding.aiResponsesGenerated': 'Les réponses IA seront générées automatiquement',
    'onboarding.goToDashboard': 'Aller au tableau de bord',
    'onboarding.addMoreLater': 'Vous pouvez toujours ajouter plus d\'emplacements ou modifier les paramètres plus tard',
    'onboarding.connectSelected': 'Connecter {count} entreprise{plural} sélectionnée{plural}',
    'onboarding.verified': 'Vérifié',
  }
} as const;

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  useEffect(() => {
    // Load saved language from localStorage
    const savedLanguage = localStorage.getItem('revally-language') as Language;
    if (savedLanguage && (savedLanguage === 'en' || savedLanguage === 'fr')) {
      setLanguage(savedLanguage);
    }
  }, []);

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('revally-language', lang);
  };

  const t = (key: TranslationKeys, params?: Record<string, string | number>) => {
    let translation: string = translations[language][key] || translations['en'][key] || key;
    
    // Handle parameter substitution
    if (params) {
      Object.entries(params).forEach(([paramKey, value]) => {
        translation = translation.replace(`{${paramKey}}`, String(value));
      });
    }
    
    return translation;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}